Assignment 1: COSC5806 W01– Data Analysis with Python (Winter 2026)

Submitted by: Manjumaney Choodali Maney

Student ID: 259600890

### Task 3: NumPy Basics: Arrays and Vectorized Computations

#### 1. ndarray

In [1]:
#Creating Arrays

import numpy as np

arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(type(arr1))


[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  #Multi-dimentional array
print(arr2)
print(arr2.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [3]:
arr3 = np.array([1, 2, 3], dtype=float) 
print(arr3)
print(arr3.dtype)   #array datatype


[1. 2. 3.]
float64


In [4]:
#array indexing and slicing

data = np.array([10, 20, 30, 40, 50])

print(data[0])
print(data[1:4])


10
[20 30 40]


In [5]:
#Boolean indexing

values = np.array([5, 12, 8, 20, 3])

filtered = values[values > 10]
print(filtered)


[12 20]


In [6]:
#Copy vs view

a = np.array([1, 2, 3, 4])
b = a[1:3]

b[:] = 99
print("a:", a)
print("b:", b)


a: [ 1 99 99  4]
b: [99 99]


In [7]:
#Array Operations

x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)
print(x * y)


[11 22 33]
[10 40 90]


#### 2. Random Numbers

In [8]:
#Basics

np.random.seed(42)

random_values = np.random.rand(5)
print(random_values)


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [9]:
#integers
random_ints = np.random.randint(1, 10, size=5)
print(random_ints)


[3 7 8 5 4]


In [10]:
#Normal distribution

normal_values = np.random.randn(5)
print(normal_values)


[ 0.39257975 -0.92918467  0.07983181 -0.1595165   0.02222183]


In [11]:
#Uniform distribution

uniform_values = np.random.uniform(low=10, high=20, size=5)
print(uniform_values)


[13.99860972 10.46665663 19.73755519 12.3277134  10.90606435]


In [12]:
#array shape

random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.61838601 0.38246199 0.98323089]
 [0.46676289 0.85994041 0.68030754]
 [0.45049925 0.01326496 0.94220176]]


In [13]:
#Shuffle data

data = np.array([1, 2, 3, 4, 5])
np.random.shuffle(data)
print(data)


[3 4 1 5 2]


In [14]:
#Random Choice

choices = np.random.choice([10, 20, 30, 40], size=3)
print(choices)


[10 20 40]


#### 3. Universal Functions

In [15]:
#Element wise operators

import numpy as np

arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.square(arr))


[1. 2. 3. 4.]
[  1  16  81 256]


In [16]:
#Absolute, Exponential, Log

values = np.array([-2, -1, 0, 1, 2])

print(np.abs(values))
print(np.exp(values))
print(np.log(np.array([1, 2, 3, 4])))


[2 1 0 1 2]
[0.13533528 0.36787944 1.         2.71828183 7.3890561 ]
[0.         0.69314718 1.09861229 1.38629436]


In [17]:
#Maximum and Minimum
a = np.array([3, 7, 2, 9])
b = np.array([5, 1, 8, 4])

print(np.maximum(a, b))
print(np.minimum(a, b))


[5 7 8 9]
[3 1 2 4]


In [18]:
#Boolean 
data = np.array([10, 15, 20, 25])

print(data > 18)
print(np.logical_and(data > 10, data < 25))


[False False  True  True]
[False  True  True False]


In [19]:
#Aggregations

nums = np.array([5, 10, 15, 20])

print(np.sum(nums))
print(np.mean(nums))
print(np.std(nums))


50
12.5
5.5901699437494745


In [20]:
#NaN Handling

arr_nan = np.array([1, np.nan, 3, np.nan])

print(np.isnan(arr_nan))
print(np.nanmean(arr_nan))


[False  True False  True]
2.0


#### 4. Array-Oriented Programming

In [21]:
#Vectorized Computation
import numpy as np

values = np.array([1, 2, 3, 4, 5])

result = values * 10
print(result)



[10 20 30 40 50]


In [22]:
#Comparing Loop vs Vectorized

# Using loop
loop_result = []
for v in values:
    loop_result.append(v * 10)

print(loop_result)


[np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


In [23]:
# Using NumPy vectorization
vectorized_result = values * 10
print(vectorized_result)


[10 20 30 40 50]


In [24]:
#Conditional Logic with Arrays

scores = np.array([45, 72, 88, 60])

status = np.where(scores >= 60, "Pass", "Fail")
print(status)


['Fail' 'Pass' 'Pass' 'Pass']


In [25]:
#Mathematical Expressions

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

expr = (x * 2) + (y / 2)
print(expr)


[4.  6.5 9. ]


In [26]:
# Boolean Masking

data = np.array([5, 12, 8, 20, 3])

filtered = data[data > 10]
print(filtered)


[12 20]


In [27]:
#Broadcasting

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

result = matrix + 10
print(result)


[[11 12 13]
 [14 15 16]]


In [28]:
#Performance-style Example
large_array = np.random.rand(1000000)

output = large_array * 3
print(output[:5])


[0.7230764  2.04979056 1.82998997 2.49958474 0.52009396]


#### 5. File I/O with Arrays

In [29]:
#Saving an Array to a File
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.save("array_data.npy", arr)


In [30]:
#Loading an Array from a File
loaded_arr = np.load("array_data.npy")
print(loaded_arr)


[10 20 30 40 50]


In [31]:
# Saving Multiple Arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.savez("multiple_arrays.npz", first=a, second=b)


In [32]:
#Loading Multiple Arrays
data = np.load("multiple_arrays.npz")

print(data["first"])
print(data["second"])


[1 2 3]
[4 5 6]


In [33]:
#Saving to Text File
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

np.savetxt("matrix.txt", matrix, delimiter=",")


In [34]:
#Loading from Text File
loaded_matrix = np.loadtxt("matrix.txt", delimiter=",")
print(loaded_matrix)


[[1. 2. 3.]
 [4. 5. 6.]]


#### 6. Linear Algebra

In [37]:
#Matrix creation


A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


In [38]:
# Matrix Addition & Multiplication
print(A + B)
print(A @ B)


[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


In [39]:
#Transpose
print(A.T)


[[1 3]
 [2 4]]


In [40]:
#Determinant

det_A = np.linalg.det(A)
print(det_A)


-2.0000000000000004


In [41]:
#Inverse

inv_A = np.linalg.inv(A)
print(inv_A)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [42]:
#Solving Linear Equations

b = np.array([5, 11])

solution = np.linalg.solve(A, b)
print(solution)


[1. 2.]


In [43]:
#Eigenvalues & Eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [44]:
#Dot Product
x = np.array([1, 2])
y = np.array([3, 4])

print(np.dot(x, y))


11


#### 7. Random Walk

In [45]:
#Simple Random Walk (1D)

np.random.seed(0)

steps = np.random.choice([1, -1], size=20)
walk = steps.cumsum()

print("Steps:", steps)
print("Random Walk:", walk)


Steps: [ 1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  1  1 -1  1  1  1  1  1 -1]
Random Walk: [ 1  0 -1  0 -1 -2 -3 -4 -5 -6 -7 -6 -5 -6 -5 -4 -3 -2 -1 -2]


In [46]:
#Random Walk with Conditions

steps = np.random.choice([1, -1], size=50)
walk = steps.cumsum()

max_value = walk.max()
min_value = walk.min()

print("Max value:", max_value)
print("Min value:", min_value)


Max value: 1
Min value: -11


In [47]:
# Find First Crossing Point
crossing_point = np.where(np.abs(walk) >= 5)[0]

if len(crossing_point) > 0:
    print("First crossing index:", crossing_point[0])
else:
    print("Threshold not crossed")


First crossing index: 18


In [48]:
#Multiple Random Walks
nwalks = 5
nsteps = 30

walks = np.random.choice([1, -1], size=(nwalks, nsteps))
walks = walks.cumsum(axis=1)

print(walks)


[[-1 -2 -1  0  1  0 -1  0 -1  0  1  0  1  0 -1 -2 -3 -4 -5 -4 -5 -6 -5 -4
  -5 -4 -3 -4 -5 -4]
 [-1  0  1  0  1  2  3  2  1  2  1  2  3  4  5  6  5  6  5  6  5  4  3  2
   1  2  1  0 -1 -2]
 [ 1  0 -1  0  1  0  1  2  3  4  3  2  3  4  3  4  3  2  1  0  1  2  3  2
   3  2  1  0  1  0]
 [ 1  2  1  2  1  0  1  2  1  2  1  2  1  2  1  2  1  2  3  4  3  4  3  4
   3  4  5  6  7  8]
 [-1  0  1  0  1  2  3  2  3  4  3  4  3  4  5  4  3  4  5  6  5  4  5  6
   7  8  9  8  9  8]]


In [49]:
#Count Walks Crossing a Threshold

hits = np.abs(walks) >= 10
num_hits = hits.any(axis=1)

print("Walks crossing threshold:", num_hits.sum())


Walks crossing threshold: 0
